# Generated by Django 3.1.12 on 2025-04-03 13:44

import bson.objectid
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FreshTakesDelicacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=5000)),
                ('pagename', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='serveTime',
            new_name='time',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.BinaryField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='Menu',
        ),
    ]
